### ISSUE TITLE
Deploy software on Digital Ocean

### ISSUE THREAD

**Issue by bfd2** [finduhclub/finduhclub#5]
Do all work for this task in a branch called issue-5

Deploy using Digital Ocean with E59 & E60:
https://courses.ics.hawaii.edu/ics314f23/morea/deployment/experience-app-deployment-digital-ocean.html

**Comment by brewerj3** [comment]
No files will be changed on GitHub for security reasons.

**Comment by brewerj3** [comment]
deployed app at http://164.92.125.147. Still need to add Robo3T and Monti APM.

**Comment by brewerj3** [comment]
Posted photos to discord.
